version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "geninsightsrepository"
    APP_NAME: "sample-fastapi"
    AWS_ACCOUNT_ID: "528503375915"
    AWS_DEFAULT_REGION: "us-west-2"
    BRANCH_NAME: "main"
    # AWS_DEFAULT_REGION: "data_lens_secrets"
    

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Fetching environment variables from Secrets Manager..."
      # - export ENV_VARS=$(aws secretsmanager get-secret-value --secret-id $BRANCH_NAME --query SecretString --output text)
  build:
    commands:
      - echo "Building Docker image for branch"
      - docker build -t $IMAGE_REPO_NAME:$APP_NAME .
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker tag $IMAGE_REPO_NAME/$APP_NAME:$BRANCH_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
