version: 0.2

env:
  variables:
    APP_NAME: "sample-fastapi"
    AWS_ACCOUNT_ID: "528503375915"
    AWS_DEFAULT_REGION: "us-west-2"

  secrets-manager:
    MILVUS_HOST: "data_lens_secrets:MILVUS_HOST"
    MILVUS_PORT: "data_lens_secrets:MILVUS_PORT"
    MILVUS_USER: "data_lens_secrets:MILVUS_USER"
    MILVUS_PASSWORD: "data_lens_secrets:MILVUS_PASSWORD"
    DATABASE_URI: "data_lens_secrets:DATABASE_URI"
    REGION: "data_lens_secrets:REGION"
    MILVUS_URI: "data_lens_secrets:MILVUS_URI"
    SECRET_KEY: "data_lens_secrets:SECRET_KEY"
    ALGORITHM: "data_lens_secrets:ALGORITHM"
    ACCESS_TOKEN_EXPIRE_MINUTES: "data_lens_secrets:ACCESS_TOKEN_EXPIRE_MINUTES"
    redis_host: "data_lens_secrets:redis_host"
    redis_port: "data_lens_secrets:redis_port"
    redis_password: "data_lens_secrets:redis_password"
    SQLALCHEMY_DATABASE_URI: "data_lens_secrets:SQLALCHEMY_DATABASE_URI"
    DB_MODEL: "data_lens_secrets:DB_MODEL"
    EMBEDDDING_MODEL: "data_lens_secrets:EMBEDDDING_MODEL"
    DATABASE_USERNAME: "data_lens_secrets:DATABASE_USERNAME"
    DATABASE_PASSWORD: "data_lens_secrets:DATABASE_PASSWORD"
    DATABASE_HOSTNAME: "data_lens_secrets:DATABASE_HOSTNAME"
    DATABASE_PORT: "data_lens_secrets:DATABASE_PORT"
    DATABASE_NAME: "data_lens_secrets:DATABASE_NAME"
    
    
    
    

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Fetching environment variables from Secrets Manager..."
      - echo "Branch name ${BRANCH_NAME}"
      #- echo "MILVUS_HOST ${MILVUS_HOST}"
      - echo "MILVUS_HOST=${MILVUS_HOST}" > .env
      - echo "MILVUS_PORT=${MILVUS_PORT}" >> .env
      - echo "MILVUS_USER=${MILVUS_USER}" >> .env
      - echo "MILVUS_PASSWORD=${MILVUS_PASSWORD}" >> .env
      - echo "DATABASE_URI=${DATABASE_URI}" >> .env
      - echo "REGION=${REGION}" >> .env
      - echo "MILVUS_URI=${MILVUS_URI}" >> .env
      - echo "SECRET_KEY=${SECRET_KEY}" >> .env
      - echo "ALGORITHM=${ALGORITHM}" >> .env
      - echo "ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}" >> .env
      - echo "redis_host=${redis_host}" >> .env
      - echo "redis_port=${redis_port}" >> .env
      - echo "redis_password=${redis_password}" >> .env
      - echo "SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}" >> .env
      - echo "DB_MODEL=${DB_MODEL}" >> .env
      - echo "EMBEDDDING_MODEL=${EMBEDDDING_MODEL}" >> .env
      - echo "DATABASE_USERNAME=${DATABASE_USERNAME}" >> .env
      - echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}" >> .env
      - echo "DATABASE_HOSTNAME=${DATABASE_HOSTNAME}" >> .env
      - echo "DATABASE_PORT=${DATABASE_PORT}" >> .env
      - echo "DATABASE_NAME=${DATABASE_NAME}" >> .env
      - echo $SAMPLE_ENV
      - echo $SAMPLE_ENV_SIMHA
      - echo "Build number, $CODEBUILD_BUILD_NUMBER"
      - LATEST_TAG=latest
      - echo "Latest tag , $LATEST_TAG"
      - IMAGE_TAG=$BRANCH_NAME_$CODEBUILD_BUILD_NUMBER 
      - echo $IMAGE_REPO_NAME
      - IMAGE_ID=$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo $IMAGE_ID

      # Print the contents of the .env file
      - echo "Contents of .env file:"
      - cat .env
      
      # - export ENV_VARS=$(aws secretsmanager get-secret-value --secret-id $BRANCH_NAME --query SecretString --output text)
  build:
    commands:
      - echo "Building Docker image for branch"
      - echo "Image tag:> $IMAGE_TAG"
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "$REPO_URI/$IMAGE_REPO_NAME/$APP_NAME:$BRANCH_NAME"
      - REPO_URL=$REPO_URI/$IMAGE_REPO_NAME:$BRANCH_NAME
      - echo $REPO_URL
      - echo $REPO_URI/$IMAGE_ID
      #- docker build -t $REPO_URL .
      
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - echo $REPO_URL
      #- docker push $REPO_URL
