version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "geninsightsrepository"
    APP_NAME: "sample-fastapi"
    AWS_ACCOUNT_ID: "528503375915"
    AWS_DEFAULT_REGION: "us-west-2"
    BRANCH_NAME:"main"
  secrets-manager:
    MILVUS_HOST: "data_lens_secrets:MILVUS_HOST"
    MILVUS_PORT: "data_lens_secrets:MILVUS_PORT"
    MILVUS_USER: "data_lens_secrets:MILVUS_USER"
    MILVUS_PASSWORD: "data_lens_secrets:MILVUS_PASSWORD"
    DATABASE_URI: "data_lens_secrets:DATABASE_URI"
    REGION: "data_lens:REGION"
    
    

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Fetching environment variables from Secrets Manager..."
      - echo "Branch name ${BRANCH_NAME}"
      - echo "MILVUS_HOST ${MILVUS_HOST}"
      
      # - export ENV_VARS=$(aws secretsmanager get-secret-value --secret-id $BRANCH_NAME --query SecretString --output text)
  build:
    commands:
      - echo "Building Docker image for branch"
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "$REPO_URI/$IMAGE_REPO_NAME/$APP_NAME:$BRANCH_NAME"
      - REPO_URL=$REPO_URI/$IMAGE_REPO_NAME:$BRANCH_NAME
      #- docker build -t $REPO_URL .
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - echo $REPO_URL
      #- docker push $REPO_URL
