services:
  sample-fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: geninsightsrepository:${TAG}
    container_name: sample_app
    restart: always
    ports:
      - 8000:8000
    environment:
      - env=dev
